FROM node:26-alpine

WORKDIR /app

COPY package.json package-lock.json ./

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm install

EXPOSE 3000

CMD [ "npx", "next", "dev" ]
